wandb_version: 1

lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713684703.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.40.0
      8:
      - 5
      13: linux-x86_64
